#!/bin/bash

echo Start
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 14 2
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 14 4
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 14 6
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 21 2
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 21 4
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 21 6
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 28 2
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 28 4
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 28 6
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 35 2
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 35 4
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 35 6
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 49 2
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 49 4
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 49 6
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 70 2
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 70 4
./dist/Debug/GNU-Linux-x86/behaviourdetectionoffline 70 6

echo End
